import { useState, useEffect } from "react";
import { Sparkles } from "lucide-react";
import api from "../api/axios";
import { formatApiError } from "../utils/apiError";
import { datetimeLocalToIso, toDatetimeLocalValue } from "../utils/datetime";

const EMPTY = {
  title: "",
  description: "",
  examples: "",
  prerequisites: "",
  difficulty: "easy",
  deadline: "",
  test_cases: [{ input_data: "", expected_output: "", is_hidden: false, order: 0, validation_type: "EXACT_MATCH", validator_type: "", verification_status: "VERIFIED", verification_reason: "" }],
};

function mapDifficulty(value) {
  const next = String(value || "").trim().toLowerCase();
  if (next === "easy" || next === "medium" || next === "hard") return next;
  return "medium";
}

function mapGeneratedTests(data) {
  const makeCase = (testCase, index, isHidden) => ({
    input_data: testCase.input,
    expected_output: testCase.output,
    is_hidden: isHidden,
    order: index,
    validation_type: "EXACT_MATCH",
    validator_type: "",
    verification_status: "VERIFIED",
    verification_reason: "Generated by AI from the problem statement and checked for complete input and output.",
  });
  return [
    ...(data.public_test_cases || []).map((testCase, index) => makeCase(testCase, index, false)),
    ...(data.hidden_test_cases || []).map((testCase, index) => makeCase(testCase, index + 2, true)),
  ];
}

export default function QuestionFormModal({ initial, onClose, onSubmit }) {
  const [form, setForm] = useState(EMPTY);
  const [saving, setSaving] = useState(false);
  const [generating, setGenerating] = useState(false);
  const [error, setError] = useState("");
  const [aiNotice, setAiNotice] = useState("");
  const [aiNoticeType, setAiNoticeType] = useState("success");
  const isEdit = Boolean(initial?.id);
  const canGenerate = Boolean((form.title || "").trim() && (form.description || "").trim() && (form.examples || "").trim()) && !generating && !saving;

  useEffect(() => {
    if (initial?.id) {
      setForm({
        ...EMPTY,
        ...initial,
        deadline: toDatetimeLocalValue(initial.deadline),
        test_cases:
          initial.test_cases?.length > 0
            ? initial.test_cases.map((tc, index) => ({
                ...tc,
                order: tc.order ?? index,
                validation_type: tc.validation_type || "EXACT_MATCH",
                validator_type: tc.validator_type || "",
              }))
            : [{ input_data: "", expected_output: "", is_hidden: false, order: 0, validation_type: "EXACT_MATCH", validator_type: "", verification_status: "VERIFIED", verification_reason: "" }],
      });
    } else {
      setForm(EMPTY);
    }
    setError("");
    setAiNotice("");
  }, [initial]);

  async function handleGenerate() {
    if (!canGenerate) return;
    setGenerating(true);
    setError("");
    setAiNotice("Analyzing problem and generating test cases...");
    setAiNoticeType("info");
    try {
      const { data } = await api.post(
        "/admin/ai/generate-question-data/",
        { title: form.title, problem_statement: form.description, examples: form.examples },
        // A complete six-case answer can take up to one minute from a
        // healthy provider; leave room for bounded fallback without aborting
        // a valid server response in the browser.
        { timeout: 210000 }
      );
      if (!data?.success || !data.data) {
        setAiNotice(data?.message || "Unable to generate question details. Please try again.");
        setAiNoticeType("error");
        return;
      }
      const generated = data.data;
      const generatedTests = mapGeneratedTests(generated);
      const publicCount = generatedTests.filter((testCase) => !testCase.is_hidden).length;
      const hiddenCount = generatedTests.filter((testCase) => testCase.is_hidden).length;
      const allComplete = generatedTests.every((testCase) => testCase.input_data.trim() && testCase.expected_output.trim());
      if (publicCount !== 2 || hiddenCount !== 4 || !allComplete) {
        setAiNotice(
          "AI did not return exactly 2 public and 4 hidden testcases with complete inputs and outputs. No incomplete testcases were added; please try again."
        );
        setAiNoticeType("error");
        return;
      }
      setForm((prev) => ({
        ...prev,
        difficulty: mapDifficulty(generated.difficulty),
        prerequisites: (generated.prerequisites || []).join("\n"),
        test_cases: generatedTests,
      }));
      setAiNotice("Generated 2 public and 4 hidden testcases with complete inputs and expected outputs. Review them, then create the question.");
      setAiNoticeType("success");
    } catch (err) {
      setAiNotice(
        err?.code === "ECONNABORTED"
          ? "AI provider did not respond in time. Please try again; no testcases were added."
          : formatApiError(err, "Unable to generate question details. Please try again.")
      );
      setAiNoticeType("error");
    } finally {
      setGenerating(false);
    }
  }


  async function handleSubmit(e) {
    e.preventDefault();
    if (saving || generating) return;
    setSaving(true);
    setError("");
    try {
      const payload = {
        ...form,
        deadline: datetimeLocalToIso(form.deadline),
      };
      await onSubmit(payload);
      onClose();
    } catch (err) {
      setError(
        formatApiError(
          err,
          isEdit ? "Failed to update question. Please try again." : "Failed to add question. Please try again."
        )
      );
    } finally {
      setSaving(false);
    }
  }

  function updateCase(index, patch) {
    const next = [...form.test_cases];
    next[index] = { ...next[index], ...patch, order: index };
    setForm({ ...form, test_cases: next });
  }

  return (
    <div className="fixed inset-0 bg-slate-900/40 flex items-center justify-center z-20 px-4">
      <div className="card w-full max-w-2xl p-6 max-h-[90vh] overflow-y-auto">
        <h2 className="text-lg font-semibold text-slate-900 mb-4">
          {isEdit ? "Edit Question" : "Create Question"}
        </h2>
        <form onSubmit={handleSubmit} className="space-y-4">
          {error && (
            <div className="bg-red-50 text-red-700 text-sm px-3 py-2 rounded-lg border border-red-200">{error}</div>
          )}
          {aiNotice && (
            <div
              className={`text-sm px-3 py-2 rounded-lg border ${
                aiNoticeType === "error"
                  ? "bg-red-50 text-red-700 border-red-200"
                  : aiNoticeType === "info"
                    ? "bg-sky-50 text-sky-800 border-sky-200"
                    : "bg-emerald-50 text-emerald-800 border-emerald-200"
              }`}
            >
              {aiNotice}
            </div>
          )}
          <div>
            <label className="block text-sm font-medium text-slate-700 mb-1">Problem Title</label>
            <input
              className="input"
              value={form.title}
              onChange={(e) => setForm({ ...form, title: e.target.value })}
              placeholder="e.g. Two Sum"
              required
            />
          </div>
          <div>
            <div className="flex items-center justify-between gap-2 mb-1">
              <label className="block text-sm font-medium text-slate-700">Description</label>
              <button
                type="button"
                onClick={handleGenerate}
                disabled={!canGenerate}
                className="inline-flex items-center gap-1.5 text-xs font-semibold text-brand-700 disabled:opacity-50 disabled:cursor-not-allowed"
              >
                <Sparkles className="h-3.5 w-3.5" />
                {generating ? "Generating..." : "✨ Generate with AI"}
              </button>
            </div>
            <textarea
              className="input"
              rows={3}
              value={form.description}
              onChange={(e) => setForm({ ...form, description: e.target.value })}
              placeholder="Describe the problem statement..."
            />
            <p className="text-xs text-slate-400 mt-1">Add the title, full problem statement, and two examples. Generate with AI creates exactly 2 public and 4 hidden cases before you create the question.</p>
          </div>
          <div>
            <label className="block text-sm font-medium text-slate-700 mb-1">Examples</label>
            <textarea
              className="input font-mono text-sm"
              rows={4}
              value={form.examples}
              onChange={(e) => setForm({ ...form, examples: e.target.value })}
              placeholder={"Example 1:\nInput: 4 9\n2 7 11 15\nOutput: 1\n\nExample 2:\nInput: 3 4\n1 4 8\nOutput: 1"}
            />
          </div>
          <div>
            <label className="block text-sm font-medium text-slate-700 mb-1">Pre-requisites</label>
            <textarea
              className="input"
              rows={2}
              value={form.prerequisites}
              onChange={(e) => setForm({ ...form, prerequisites: e.target.value })}
              placeholder="e.g. Arrays, Hash Map"
            />
          </div>
          <div>
            <label className="block text-sm font-medium text-slate-700 mb-1">Difficulty</label>
            <select
              className="input"
              value={form.difficulty}
              onChange={(e) => setForm({ ...form, difficulty: e.target.value })}
            >
              <option value="easy">Easy</option>
              <option value="medium">Medium</option>
              <option value="hard">Hard</option>
            </select>
          </div>
          <div>
            <label className="block text-sm font-medium text-slate-700 mb-1">Deadline</label>
            <input
              className="input"
              type="datetime-local"
              value={form.deadline}
              onChange={(e) => setForm({ ...form, deadline: e.target.value })}
              required
            />
            <p className="text-xs text-slate-400 mt-1">Students earn points only for proofs submitted before this time.</p>
          </div>
          <div>
            <div className="flex items-center justify-between mb-2">
              <label className="block text-sm font-medium text-slate-700">Test cases</label>
              <button
                type="button"
                className="text-xs font-medium text-brand-700"
                onClick={() =>
                  setForm({
                    ...form,
                    test_cases: [
                      ...(form.test_cases || []),
                      {
                        input_data: "",
                        expected_output: "",
                        is_hidden: false,
                        order: (form.test_cases || []).length,
                        validation_type: "EXACT_MATCH",
                        validator_type: "",
                        verification_status: "VERIFIED",
                        verification_reason: "",
                      },
                    ],
                  })
                }
              >
                + Add test case
              </button>
            </div>
            <p className="text-xs text-slate-400 mb-2">
              Generate with AI replaces this list with exactly 2 public and 4 hidden cases, each with complete input and expected output. Public cases are available to Run Code; hidden cases run only on Submit.
            </p>
            <div className="space-y-3">
              {(form.test_cases || []).map((tc, index) => (
                <div key={index} className="rounded-lg border border-slate-200 p-3 space-y-2 bg-slate-50">
                  <div className="flex items-center justify-between gap-2">
                    <span className="text-xs font-semibold text-slate-600">Case {index + 1}</span>
                    <div className="flex items-center gap-3">
                      <label className="text-xs text-slate-600 inline-flex items-center gap-1">
                        <input
                          type="checkbox"
                          checked={Boolean(tc.is_hidden)}
                          onChange={(e) => updateCase(index, { is_hidden: e.target.checked })}
                        />
                        Hidden
                      </label>
                      {form.test_cases.length > 1 && (
                        <button
                          type="button"
                          className="text-xs text-rose-600"
                          onClick={() =>
                            setForm({
                              ...form,
                              test_cases: form.test_cases.filter((_, i) => i !== index),
                            })
                          }
                        >
                          Remove
                        </button>
                      )}
                    </div>
                  </div>
                  <select
                    className="input text-xs"
                    value={tc.validation_type || "EXACT_MATCH"}
                    onChange={(e) => {
                      const validation_type = e.target.value;
                      updateCase(index, {
                        validation_type,
                        validator_type: validation_type === "CUSTOM_VALIDATOR" ? (tc.validator_type || "PEAK_2D") : "",
                      });
                    }}
                  >
                    <option value="EXACT_MATCH">Exact match</option>
                    <option value="CUSTOM_VALIDATOR">Custom validator</option>
                  </select>
                  <select
                    className="input text-xs"
                    value={tc.verification_status || "GENERATED"}
                    onChange={(e) => updateCase(index, { verification_status: e.target.value })}
                    aria-label={`Verification status for case ${index + 1}`}
                  >
                    <option value="VERIFIED">Verified</option>
                    <option value="REQUIRES_REVIEW">Requires admin review</option>
                    <option value="GENERATED">Generated</option>
                    <option value="INVALID">Invalid (do not publish)</option>
                  </select>
                  {tc.verification_reason && (
                    <p className="text-xs text-amber-700">{tc.verification_reason}</p>
                  )}
                  {tc.validation_type === "CUSTOM_VALIDATOR" && (
                    <select
                      className="input text-xs"
                      value={tc.validator_type || "PEAK_2D"}
                      onChange={(e) => updateCase(index, { validator_type: e.target.value })}
                    >
                      <option value="PEAK_2D">PEAK_2D</option>
                    </select>
                  )}
                  <textarea
                    className="input font-mono text-xs"
                    rows={2}
                    placeholder="stdin"
                    value={tc.input_data}
                    onChange={(e) => updateCase(index, { input_data: e.target.value })}
                  />
                  <textarea
                    className="input font-mono text-xs"
                    rows={2}
                    placeholder={tc.validation_type === "CUSTOM_VALIDATOR" ? "expected stdout (optional)" : "expected stdout"}
                    value={tc.expected_output}
                    onChange={(e) => updateCase(index, { expected_output: e.target.value })}
                    required={tc.validation_type !== "CUSTOM_VALIDATOR"}
                  />
                </div>
              ))}
            </div>
          </div>
          <div className="flex justify-end gap-2 pt-2">
            <button type="button" onClick={onClose} className="btn btn-secondary" disabled={generating}>
              Cancel
            </button>
            <button type="submit" disabled={saving || generating} className="btn btn-primary">
              {saving ? "Saving..." : isEdit ? "Save Changes" : "Create Question"}
            </button>
          </div>
        </form>
      </div>
    </div>
  );
}
