DIFFICULTIES = ("Easy", "Medium", "Hard")
VALIDATION_EXACT = "EXACT_MATCH"
VALIDATION_CUSTOM = "CUSTOM_VALIDATOR"
VALIDATION_TYPES = (VALIDATION_EXACT, VALIDATION_CUSTOM)

MAX_FIELD_CHARS = 20_000
MAX_HIDDEN_INPUT_CHARS = 50_000

# The authoring flow always needs a predictable six-case starter set.
PUBLIC_TEST_RANGE = (2, 2)
HIDDEN_TEST_RANGE = (4, 4)
EXAMPLE_RANGE = (2, 4)
