# Generated by Django 5.1.4 on 2026-08-26 09:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='problem_link',
        ),
        migrations.AddField(
            model_name='assignment',
            name='linkedin_post_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='proof_status',
            field=models.CharField(choices=[('none', 'Not Submitted'), ('pending', 'Pending Review'), ('validated', 'Validated')], db_index=True, default='none', max_length=15),
        ),
        migrations.AddField(
            model_name='assignment',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='validated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='examples',
            field=models.TextField(blank=True, help_text='Sample inputs/outputs for the problem'),
        ),
        migrations.AddField(
            model_name='question',
            name='prerequisites',
            field=models.TextField(blank=True, help_text='Topics/skills needed before attempting'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['proof_status'], name='core_assign_proof_s_189fc7_idx'),
        ),
    ]
