# Generated by Django 5.1.4 on 2026-09-14 19:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_profile_normalized_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('event_type', models.CharField(choices=[('AUTH_LOGIN_SUCCESS', 'Authentication login succeeded'), ('AUTH_LOGIN_FAILURE', 'Authentication login failed'), ('AUTH_LOGOUT', 'Authentication logout'), ('AUTH_REFRESH_FAILURE', 'Authentication refresh failed'), ('AUTH_GOOGLE_FAILURE', 'Google authentication failed'), ('AUTH_TOKEN_FAILURE', 'Authentication token failed'), ('AUTH_PERMISSION_DENIED', 'Authorization denied'), ('AUTH_OBJECT_ACCESS_DENIED', 'Object access denied'), ('AUTH_REMOVED_ACCOUNT_ACCESS', 'Removed account access'), ('CODE_EXECUTION', 'Code execution'), ('CODE_EXECUTION_THROTTLED', 'Code execution throttled'), ('CODE_SUBMISSION', 'Code submission'), ('CODE_SUBMISSION_THROTTLED', 'Code submission throttled'), ('AI_GENERATION', 'AI generation'), ('AI_GENERATION_THROTTLED', 'AI generation throttled'), ('VALIDATION_FAILURE', 'Validation failed'), ('RATE_LIMIT_EXCEEDED', 'Rate limit exceeded'), ('SERVER_ERROR', 'Server error')], db_index=True, max_length=40)),
                ('success', models.BooleanField(db_index=True, default=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('request_path', models.CharField(blank=True, max_length=255)),
                ('http_method', models.CharField(blank=True, max_length=10)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type', '-created_at'], name='core_audit_event_created_idx'), models.Index(fields=['user', '-created_at'], name='core_audit_user_created_idx')],
            },
        ),
    ]
